# Generated by Django 3.1.7 on 2022-07-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
