# Generated by Django 3.1.7 on 2022-07-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
